# Generated by Django 4.2 on 2023-07-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateYourOwnPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_tomato_sauce', models.BooleanField(blank=True, null=True)),
                ('has_cheese', models.CharField(blank=True, choices=[('Mozzarella', 'Mozzarella'), ('Parmigiano', 'Parmigiano'), ('Cottage', 'Cottage'), ('Cheddar', 'Cheddar'), ('Emmental', 'Emmental')], max_length=10, null=True)),
                ('dough', models.CharField(choices=[('Neapolitan', 'Neapolitan'), ('Gluten Free', 'Gluten Free'), ('Sicilian', 'Sicilian'), ('Whole Wheat', 'Whole Wheat'), ('Dietary', 'Dietary')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough', models.CharField(max_length=40)),
                ('tomato_sauce', models.BooleanField(blank=True, null=True)),
                ('cheese_type', models.CharField(max_length=40)),
                ('meat_type', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
