# Generated by Django 4.2 on 2023-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createyourownpizza',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
