# Generated by Django 4.2 on 2023-07-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_createyourownpizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createyourownpizza',
            name='pizza_name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
