# Generated by Django 4.2 on 2023-07-23 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_createyourownpizza_pizza_name_pizza_pizza_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='createyourownpizza',
            name='user_pk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
