# Generated by Django 4.2 on 2023-07-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='tomato_sauce',
        ),
    ]
