# Generated by Django 4.2 on 2023-07-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_pizza_tomato_sauce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createyourownpizza',
            name='has_tomato_sauce',
        ),
        migrations.AddField(
            model_name='pizza',
            name='tomato_sauce',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
