# Generated by Django 4.2 on 2023-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_createyourownpizza_has_tomato_sauce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createyourownpizza',
            name='topping',
            field=models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Sausage', 'Sausage'), ('Olives', 'Olives')], default='ok', max_length=20),
            preserve_default=False,
        ),
    ]
